//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResTB.Translation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResTB.Translation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After mitigation.
        /// </summary>
        public static string After_Mitigation {
            get {
                return ResourceManager.GetString("After_Mitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiResiliencia Files.
        /// </summary>
        public static string App_Files {
            get {
                return ResourceManager.GetString("App_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiResiliencia.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiResiliencia.
        /// </summary>
        public static string App_Name_ES {
            get {
                return ResourceManager.GetString("App_Name_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk and Cost-Efficiency Analysis of Disaster Risk Reduction Measures.
        /// </summary>
        public static string App_Teaser {
            get {
                return ResourceManager.GetString("App_Teaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis del Riesgo y de la Costo-eficiencia de Medidas para Reducción de Riesgos a Desastres.
        /// </summary>
        public static string App_Teaser_ES {
            get {
                return ResourceManager.GetString("App_Teaser_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before mitigation.
        /// </summary>
        public static string Before_Mitigation {
            get {
                return ResourceManager.GetString("Before_Mitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database contains default values.
        /// </summary>
        public static string Check_Database_Default {
            get {
                return ResourceManager.GetString("Check_Database_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database contains modified default values.
        /// </summary>
        public static string Check_Database_Default_No {
            get {
                return ResourceManager.GetString("Check_Database_Default_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified default values.
        /// </summary>
        public static string Check_Database_Default_NOK {
            get {
                return ResourceManager.GetString("Check_Database_Default_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default values OK.
        /// </summary>
        public static string Check_Database_Default_OK {
            get {
                return ResourceManager.GetString("Check_Database_Default_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software is signed.
        /// </summary>
        public static string Check_Signature {
            get {
                return ResourceManager.GetString("Check_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software is not signed.
        /// </summary>
        public static string Check_SignatureNone {
            get {
                return ResourceManager.GetString("Check_SignatureNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Coord_Go {
            get {
                return ResourceManager.GetString("Coord_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to coordinates.
        /// </summary>
        public static string Coord_Goto {
            get {
                return ResourceManager.GetString("Coord_Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Coord_Lat {
            get {
                return ResourceManager.GetString("Coord_Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude in degrees (WGS84).
        /// </summary>
        public static string Coord_Lat_WGS {
            get {
                return ResourceManager.GetString("Coord_Lat_WGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Coord_Long {
            get {
                return ResourceManager.GetString("Coord_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude in degrees (WGS84).
        /// </summary>
        public static string Coord_Long_WGS {
            get {
                return ResourceManager.GetString("Coord_Long_WGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage potential.
        /// </summary>
        public static string DamagePotential {
            get {
                return ResourceManager.GetString("DamagePotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of damage potential.
        /// </summary>
        public static string DamagePotential_Mapping {
            get {
                return ResourceManager.GetString("DamagePotential_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string DamagePotential_Object {
            get {
                return ResourceManager.GetString("DamagePotential_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry type.
        /// </summary>
        public static string DamagePotential_ObjectGeometry {
            get {
                return ResourceManager.GetString("DamagePotential_ObjectGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object class.
        /// </summary>
        public static string DamagePotential_Objektclass {
            get {
                return ResourceManager.GetString("DamagePotential_Objektclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected damage potential.
        /// </summary>
        public static string DamagePotential_Selected {
            get {
                return ResourceManager.GetString("DamagePotential_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit geometry.
        /// </summary>
        public static string Edit_Geometry {
            get {
                return ResourceManager.GetString("Edit_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        public static string Geometry {
            get {
                return ResourceManager.GetString("Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoNames (offline).
        /// </summary>
        public static string GeoNames_DB {
            get {
                return ResourceManager.GetString("GeoNames_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string GUI_Help {
            get {
                return ResourceManager.GetString("GUI_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard map.
        /// </summary>
        public static string Hazard_Map {
            get {
                return ResourceManager.GetString("Hazard_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of hazard maps.
        /// </summary>
        public static string Hazard_Map_Mapping {
            get {
                return ResourceManager.GetString("Hazard_Map_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected hazard map.
        /// </summary>
        public static string Hazard_Map_Selected {
            get {
                return ResourceManager.GetString("Hazard_Map_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard maps (after measure).
        /// </summary>
        public static string Hazard_Maps_after_Measure {
            get {
                return ResourceManager.GetString("Hazard_Maps_after_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard maps (before measure).
        /// </summary>
        public static string Hazard_Maps_before_Measure {
            get {
                return ResourceManager.GetString("Hazard_Maps_before_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard index.
        /// </summary>
        public static string HazardIndex {
            get {
                return ResourceManager.GetString("HazardIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on other damage potentials to transfer resilience values.
        /// </summary>
        public static string Info_Copy_Resilience {
            get {
                return ResourceManager.GetString("Info_Copy_Resilience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to minimize.
        /// </summary>
        public static string Info_DoubleClick_Minimize {
            get {
                return ResourceManager.GetString("Info_DoubleClick_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete geometry (after selection).
        /// </summary>
        public static string Info_Edit_Delete {
            get {
                return ResourceManager.GetString("Info_Edit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End editing.
        /// </summary>
        public static string Info_Edit_End {
            get {
                return ResourceManager.GetString("Info_Edit_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to close the polygon , ESC key to delete faulty polygons.
        /// </summary>
        public static string Info_Edit_Polygone {
            get {
                return ResourceManager.GetString("Info_Edit_Polygone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Info_Edit_Undo {
            get {
                return ResourceManager.GetString("Info_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        public static string Intensity_high {
            get {
                return ResourceManager.GetString("Intensity_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low.
        /// </summary>
        public static string Intensity_low {
            get {
                return ResourceManager.GetString("Intensity_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string Intensity_medium {
            get {
                return ResourceManager.GetString("Intensity_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit layer to view.
        /// </summary>
        public static string Layer_Fit {
            get {
                return ResourceManager.GetString("Layer_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide layer.
        /// </summary>
        public static string Layer_Hide {
            get {
                return ResourceManager.GetString("Layer_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer management.
        /// </summary>
        public static string Layer_Management {
            get {
                return ResourceManager.GetString("Layer_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move layer to the bottom.
        /// </summary>
        public static string Layer_Move_Bottom {
            get {
                return ResourceManager.GetString("Layer_Move_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move layer down.
        /// </summary>
        public static string Layer_Move_Down {
            get {
                return ResourceManager.GetString("Layer_Move_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move layer to the top.
        /// </summary>
        public static string Layer_Move_Top {
            get {
                return ResourceManager.GetString("Layer_Move_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move layer up.
        /// </summary>
        public static string Layer_Move_Up {
            get {
                return ResourceManager.GetString("Layer_Move_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove layer.
        /// </summary>
        public static string Layer_Remove {
            get {
                return ResourceManager.GetString("Layer_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show layer.
        /// </summary>
        public static string Layer_Show {
            get {
                return ResourceManager.GetString("Layer_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map control.
        /// </summary>
        public static string Map_Control {
            get {
                return ResourceManager.GetString("Map_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Extent.
        /// </summary>
        public static string Map_Extent {
            get {
                return ResourceManager.GetString("Map_Extent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping.
        /// </summary>
        public static string Map_Mapping {
            get {
                return ResourceManager.GetString("Map_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        public static string Map_Pan {
            get {
                return ResourceManager.GetString("Map_Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online map provider.
        /// </summary>
        public static string Map_Provider {
            get {
                return ResourceManager.GetString("Map_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by polygon.
        /// </summary>
        public static string Map_SelectByPolygon {
            get {
                return ResourceManager.GetString("Map_SelectByPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Map_Selection {
            get {
                return ResourceManager.GetString("Map_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string Map_Zoom_In {
            get {
                return ResourceManager.GetString("Map_Zoom_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string Map_Zoom_Out {
            get {
                return ResourceManager.GetString("Map_Zoom_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage potentials added.
        /// </summary>
        public static string MapControl_AddedDamagePotentials {
            get {
                return ResourceManager.GetString("MapControl_AddedDamagePotentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter added.
        /// </summary>
        public static string MapControl_AddedPerimeter {
            get {
                return ResourceManager.GetString("MapControl_AddedPerimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding hazard maps.
        /// </summary>
        public static string MapControl_AddingHazardMaps {
            get {
                return ResourceManager.GetString("MapControl_AddingHazardMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding project layers.
        /// </summary>
        public static string MapControl_AddProjectLayers {
            get {
                return ResourceManager.GetString("MapControl_AddProjectLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster reprojection.
        /// </summary>
        public static string MapControl_Busy_RasterReprojection {
            get {
                return ResourceManager.GetString("MapControl_Busy_RasterReprojection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting raster reprojection.
        /// </summary>
        public static string MapControl_Busy_StartRasterReprojection {
            get {
                return ResourceManager.GetString("MapControl_Busy_StartRasterReprojection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open layer.
        /// </summary>
        public static string MapControl_Error_CouldNotAddLayer {
            get {
                return ResourceManager.GetString("MapControl_Error_CouldNotAddLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to database.
        /// </summary>
        public static string MapControl_Error_CouldNotConnectDatabase {
            get {
                return ResourceManager.GetString("MapControl_Error_CouldNotConnectDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add layer.
        /// </summary>
        public static string MapControl_Error_CouldNotLoadLayer {
            get {
                return ResourceManager.GetString("MapControl_Error_CouldNotLoadLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run SQL Query.
        /// </summary>
        public static string MapControl_Error_EditingNotAllowed {
            get {
                return ResourceManager.GetString("MapControl_Error_EditingNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing database connection configuration.
        /// </summary>
        public static string MapControl_Error_EditingNotSupported {
            get {
                return ResourceManager.GetString("MapControl_Error_EditingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reproject layer.
        /// </summary>
        public static string MapControl_Error_FailedToRunSQLQuery {
            get {
                return ResourceManager.GetString("MapControl_Error_FailedToRunSQLQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing of dynamically loaded OGR layers isn&apos;t allowed..
        /// </summary>
        public static string MapControl_Error_GdalWarpError {
            get {
                return ResourceManager.GetString("MapControl_Error_GdalWarpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Import or Export project.
        /// </summary>
        public static string MapControl_Error_ImportExportError {
            get {
                return ResourceManager.GetString("MapControl_Error_ImportExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGR layer doesn&apos;t support editing.
        /// </summary>
        public static string MapControl_Error_MissingDBConfiguration {
            get {
                return ResourceManager.GetString("MapControl_Error_MissingDBConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape invalid.
        /// </summary>
        public static string MapControl_Error_ShapeInvalid {
            get {
                return ResourceManager.GetString("MapControl_Error_ShapeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined error.
        /// </summary>
        public static string MapControl_Error_UndefinedError {
            get {
                return ResourceManager.GetString("MapControl_Error_UndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use StartEditing first.
        /// </summary>
        public static string MapControl_Error_UseStartEditing {
            get {
                return ResourceManager.GetString("MapControl_Error_UseStartEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported Project Database.
        /// </summary>
        public static string MapControl_Exporting_Database {
            get {
                return ResourceManager.GetString("MapControl_Exporting_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project exportet to.
        /// </summary>
        public static string MapControl_Exporting_ExportetTo {
            get {
                return ResourceManager.GetString("MapControl_Exporting_ExportetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting layers.
        /// </summary>
        public static string MapControl_Exporting_Layers {
            get {
                return ResourceManager.GetString("MapControl_Exporting_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing project.
        /// </summary>
        public static string MapControl_Importing {
            get {
                return ResourceManager.GetString("MapControl_Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project imported.
        /// </summary>
        public static string MapControl_Importing_Success {
            get {
                return ResourceManager.GetString("MapControl_Importing_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map refreshed.
        /// </summary>
        public static string MapControl_MapRefreshed {
            get {
                return ResourceManager.GetString("MapControl_MapRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project loaded.
        /// </summary>
        public static string MapControl_ProjectLoaded {
            get {
                return ResourceManager.GetString("MapControl_ProjectLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redrawing map.
        /// </summary>
        public static string MapControl_RedrawMap {
            get {
                return ResourceManager.GetString("MapControl_RedrawMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading layers.
        /// </summary>
        public static string MapControl_ReloadLayers {
            get {
                return ResourceManager.GetString("MapControl_ReloadLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation measure.
        /// </summary>
        public static string MitigationMeasure {
            get {
                return ResourceManager.GetString("MitigationMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction costs.
        /// </summary>
        public static string MM_Costs {
            get {
                return ResourceManager.GetString("MM_Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life span [years].
        /// </summary>
        public static string MM_LifeSpan {
            get {
                return ResourceManager.GetString("MM_LifeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance costs per year.
        /// </summary>
        public static string MM_MaintenanceCosts {
            get {
                return ResourceManager.GetString("MM_MaintenanceCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total yearly costs.
        /// </summary>
        public static string MM_YearlyCosts {
            get {
                return ResourceManager.GetString("MM_YearlyCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database OK.
        /// </summary>
        public static string Msg_Db_Connected {
            get {
                return ResourceManager.GetString("Msg_Db_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Database.
        /// </summary>
        public static string Msg_Db_Disconnected {
            get {
                return ResourceManager.GetString("Msg_Db_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet.
        /// </summary>
        public static string Msg_Internet_No {
            get {
                return ResourceManager.GetString("Msg_Internet_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet OK.
        /// </summary>
        public static string Msg_Internet_Ok {
            get {
                return ResourceManager.GetString("Msg_Internet_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Msg_Question {
            get {
                return ResourceManager.GetString("Msg_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue anyway?.
        /// </summary>
        public static string Msg_QuestionContinue {
            get {
                return ResourceManager.GetString("Msg_QuestionContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the currently selected project..
        /// </summary>
        public static string Msg_QuestionDeleteProject {
            get {
                return ResourceManager.GetString("Msg_QuestionDeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural hazard.
        /// </summary>
        public static string NatHazard {
            get {
                return ResourceManager.GetString("NatHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of floors.
        /// </summary>
        public static string OP_Floors {
            get {
                return ResourceManager.GetString("OP_Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name.
        /// </summary>
        public static string OP_Name {
            get {
                return ResourceManager.GetString("OP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivation to change person per floor.
        /// </summary>
        public static string OP_PersonChange {
            get {
                return ResourceManager.GetString("OP_PersonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons per floor / vehicle.
        /// </summary>
        public static string OP_PersonFloor {
            get {
                return ResourceManager.GetString("OP_PersonFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person precense [hours/day].
        /// </summary>
        public static string OP_Presence {
            get {
                return ResourceManager.GetString("OP_Presence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily operating loss.
        /// </summary>
        public static string OP_Staffs {
            get {
                return ResourceManager.GetString("OP_Staffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity of object.
        /// </summary>
        public static string OP_Unity {
            get {
                return ResourceManager.GetString("OP_Unity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivation to change value.
        /// </summary>
        public static string OP_ValueChange {
            get {
                return ResourceManager.GetString("OP_ValueChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual value / unit.
        /// </summary>
        public static string OP_ValuePerUnit {
            get {
                return ResourceManager.GetString("OP_ValuePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of vehicles / day.
        /// </summary>
        public static string OP_Vehicles {
            get {
                return ResourceManager.GetString("OP_Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average speed [km/h].
        /// </summary>
        public static string OP_VehicleSpeed {
            get {
                return ResourceManager.GetString("OP_VehicleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter.
        /// </summary>
        public static string Perimeter {
            get {
                return ResourceManager.GetString("Perimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select please....
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        public static string Polygon {
            get {
                return ResourceManager.GetString("Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string Project_Create {
            get {
                return ResourceManager.GetString("Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project.
        /// </summary>
        public static string Project_Delete {
            get {
                return ResourceManager.GetString("Project_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export project.
        /// </summary>
        public static string Project_Export {
            get {
                return ResourceManager.GetString("Project_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to PDF.
        /// </summary>
        public static string Project_ExportPDF {
            get {
                return ResourceManager.GetString("Project_ExportPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import project.
        /// </summary>
        public static string Project_Import {
            get {
                return ResourceManager.GetString("Project_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project layers.
        /// </summary>
        public static string Project_Layers {
            get {
                return ResourceManager.GetString("Project_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project list.
        /// </summary>
        public static string Project_List {
            get {
                return ResourceManager.GetString("Project_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project management.
        /// </summary>
        public static string Project_Management {
            get {
                return ResourceManager.GetString("Project_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string Project_Name {
            get {
                return ResourceManager.GetString("Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string Project_New {
            get {
                return ResourceManager.GetString("Project_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project number.
        /// </summary>
        public static string Project_Number {
            get {
                return ResourceManager.GetString("Project_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string Project_Open {
            get {
                return ResourceManager.GetString("Project_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project perimeter.
        /// </summary>
        public static string Project_Perimeter {
            get {
                return ResourceManager.GetString("Project_Perimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print view.
        /// </summary>
        public static string Project_Print {
            get {
                return ResourceManager.GetString("Project_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        public static string Project_Save {
            get {
                return ResourceManager.GetString("Project_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add raster file.
        /// </summary>
        public static string Raster_Add {
            get {
                return ResourceManager.GetString("Raster_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasters.
        /// </summary>
        public static string Rasters {
            get {
                return ResourceManager.GetString("Rasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience.
        /// </summary>
        public static string Resilience {
            get {
                return ResourceManager.GetString("Resilience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience (after measure).
        /// </summary>
        public static string Resilience_after_Measure {
            get {
                return ResourceManager.GetString("Resilience_after_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience (before measure).
        /// </summary>
        public static string Resilience_before_Measure {
            get {
                return ResourceManager.GetString("Resilience_before_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer resilience to other damage potential.
        /// </summary>
        public static string Resilience_Copy {
            get {
                return ResourceManager.GetString("Resilience_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer resilience to all damage potentials.
        /// </summary>
        public static string Resilience_CopyAll {
            get {
                return ResourceManager.GetString("Resilience_CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will only overwrite the values after mitigation..
        /// </summary>
        public static string Resilience_CopyDetail_After {
            get {
                return ResourceManager.GetString("Resilience_CopyDetail_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will only overwrite the values before and after mitigation..
        /// </summary>
        public static string Resilience_CopyDetail_Before {
            get {
                return ResourceManager.GetString("Resilience_CopyDetail_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Resilience_Criteria {
            get {
                return ResourceManager.GetString("Resilience_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity index.
        /// </summary>
        public static string Resilience_Index {
            get {
                return ResourceManager.GetString("Resilience_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance factor.
        /// </summary>
        public static string Resilience_Relevance {
            get {
                return ResourceManager.GetString("Resilience_Relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social capacity.
        /// </summary>
        public static string Resilience_SocialCapacity {
            get {
                return ResourceManager.GetString("Resilience_SocialCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation finished..
        /// </summary>
        public static string Result_CalcFinished {
            get {
                return ResourceManager.GetString("Result_CalcFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation started....
        /// </summary>
        public static string Result_CalcStarted {
            get {
                return ResourceManager.GetString("Result_CalcStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Result_Header {
            get {
                return ResourceManager.GetString("Result_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensitiy maps created..
        /// </summary>
        public static string Result_IntensMapCreated {
            get {
                return ResourceManager.GetString("Result_IntensMapCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show calculation.
        /// </summary>
        public static string Result_ShowCalc {
            get {
                return ResourceManager.GetString("Result_ShowCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show calculation with details.
        /// </summary>
        public static string Result_ShowCalcDetails {
            get {
                return ResourceManager.GetString("Result_ShowCalcDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk map.
        /// </summary>
        public static string RiskMap {
            get {
                return ResourceManager.GetString("RiskMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riskmap (after measure).
        /// </summary>
        public static string RiskMapWithMitigationMeasure {
            get {
                return ResourceManager.GetString("RiskMapWithMitigationMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riskmap (before measure).
        /// </summary>
        public static string RiskMapWithoutMitigationMeasure {
            get {
                return ResourceManager.GetString("RiskMapWithoutMitigationMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search hits.
        /// </summary>
        public static string Search_Hits {
            get {
                return ResourceManager.GetString("Search_Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Tab_Map {
            get {
                return ResourceManager.GetString("Tab_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
