//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResTB_API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResFormat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResFormat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResTB_API.Resources.ResFormat", typeof(ResFormat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:C0}.
        /// </summary>
        public static string DF_Currency {
            get {
                return ResourceManager.GetString("DF_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:C0} /a.
        /// </summary>
        public static string DF_CurrencyPerYear {
            get {
                return ResourceManager.GetString("DF_CurrencyPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0}.
        /// </summary>
        public static string DF_F0 {
            get {
                return ResourceManager.GetString("DF_F0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F1}.
        /// </summary>
        public static string DF_F1 {
            get {
                return ResourceManager.GetString("DF_F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2}.
        /// </summary>
        public static string DF_F2 {
            get {
                return ResourceManager.GetString("DF_F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F3}.
        /// </summary>
        public static string DF_F3 {
            get {
                return ResourceManager.GetString("DF_F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F3} m.
        /// </summary>
        public static string DF_Meter_F3 {
            get {
                return ResourceManager.GetString("DF_Meter_F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F3} m².
        /// </summary>
        public static string DF_Meter2_F3 {
            get {
                return ResourceManager.GetString("DF_Meter2_F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2}%.
        /// </summary>
        public static string DF_PercentF3 {
            get {
                return ResourceManager.GetString("DF_PercentF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /a.
        /// </summary>
        public static string DF_PerYear {
            get {
                return ResourceManager.GetString("DF_PerYear", resourceCulture);
            }
        }
    }
}
