//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResTB_API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResTB_API.Resources.ResModel", typeof(ResModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string DE_Area {
            get {
                return ResourceManager.GetString("DE_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipped.
        /// </summary>
        public static string DE_Clipped {
            get {
                return ResourceManager.GetString("DE_Clipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of Death.
        /// </summary>
        public static string DE_DeathProbability {
            get {
                return ResourceManager.GetString("DE_DeathProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        public static string DE_Deaths {
            get {
                return ResourceManager.GetString("DE_Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of floors.
        /// </summary>
        public static string DE_Floors {
            get {
                return ResourceManager.GetString("DE_Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Damage (w/o Resilience).
        /// </summary>
        public static string DE_IndirectDamage {
            get {
                return ResourceManager.GetString("DE_IndirectDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string DE_Intensity {
            get {
                return ResourceManager.GetString("DE_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string DE_Length {
            get {
                return ResourceManager.GetString("DE_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string DE_Log {
            get {
                return ResourceManager.GetString("DE_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Death Prob..
        /// </summary>
        public static string DE_LogDeathProbability {
            get {
                return ResourceManager.GetString("DE_LogDeathProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Deaths.
        /// </summary>
        public static string DE_LogDeaths {
            get {
                return ResourceManager.GetString("DE_LogDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Indirect.
        /// </summary>
        public static string DE_LogIndirectDamage {
            get {
                return ResourceManager.GetString("DE_LogIndirectDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Person Damage.
        /// </summary>
        public static string DE_LogPersonDamage {
            get {
                return ResourceManager.GetString("DE_LogPersonDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Property Damage.
        /// </summary>
        public static string DE_LogPropertyDamage {
            get {
                return ResourceManager.GetString("DE_LogPropertyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Resilience.
        /// </summary>
        public static string DE_LogResilienceFactor {
            get {
                return ResourceManager.GetString("DE_LogResilienceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Indirect Damage (with Resilience).
        /// </summary>
        public static string DE_LogResilientIndirectDamage {
            get {
                return ResourceManager.GetString("DE_LogResilientIndirectDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Potential.
        /// </summary>
        public static string DE_MappedObject {
            get {
                return ResourceManager.GetString("DE_MappedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string DE_Part {
            get {
                return ResourceManager.GetString("DE_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occupancy.
        /// </summary>
        public static string DE_PersonCount {
            get {
                return ResourceManager.GetString("DE_PersonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Damage.
        /// </summary>
        public static string DE_PersonDamage {
            get {
                return ResourceManager.GetString("DE_PersonDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece.
        /// </summary>
        public static string DE_Piece {
            get {
                return ResourceManager.GetString("DE_Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem description.
        /// </summary>
        public static string DE_ProblemDescription {
            get {
                return ResourceManager.GetString("DE_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Damage.
        /// </summary>
        public static string DE_PropertyDamage {
            get {
                return ResourceManager.GetString("DE_PropertyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience Factor.
        /// </summary>
        public static string DE_ResilienceFactor {
            get {
                return ResourceManager.GetString("DE_ResilienceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Damage (with Resilience).
        /// </summary>
        public static string DE_ResilientIndirectDamage {
            get {
                return ResourceManager.GetString("DE_ResilientIndirectDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily operating loss.
        /// </summary>
        public static string DE_Staff {
            get {
                return ResourceManager.GetString("DE_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string IK_Years {
            get {
                return ResourceManager.GetString("IK_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Hazard.
        /// </summary>
        public static string PA_Hazard {
            get {
                return ResourceManager.GetString("PA_Hazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Likelihood of Occurrence.
        /// </summary>
        public static string PA_PrA {
            get {
                return ResourceManager.GetString("PA_PrA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Period.
        /// </summary>
        public static string PA_ReturnPeriod {
            get {
                return ResourceManager.GetString("PA_ReturnPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PA_Value {
            get {
                return ResourceManager.GetString("PA_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Costs.
        /// </summary>
        public static string PM_Costs {
            get {
                return ResourceManager.GetString("PM_Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PM_Description {
            get {
                return ResourceManager.GetString("PM_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Span.
        /// </summary>
        public static string PM_LifeSpan {
            get {
                return ResourceManager.GetString("PM_LifeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Total Yearly Costs.
        /// </summary>
        public static string PM_LogYearlyCosts {
            get {
                return ResourceManager.GetString("PM_LogYearlyCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Costs.
        /// </summary>
        public static string PM_MaintenanceCosts {
            get {
                return ResourceManager.GetString("PM_MaintenanceCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Costs.
        /// </summary>
        public static string PM_OperatingCosts {
            get {
                return ResourceManager.GetString("PM_OperatingCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate of Return.
        /// </summary>
        public static string PM_RateOfReturn {
            get {
                return ResourceManager.GetString("PM_RateOfReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Added Tax.
        /// </summary>
        public static string PM_ValueAddedTax {
            get {
                return ResourceManager.GetString("PM_ValueAddedTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Yearly Costs.
        /// </summary>
        public static string PM_YearlyCosts {
            get {
                return ResourceManager.GetString("PM_YearlyCosts", resourceCulture);
            }
        }
    }
}
