//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResTB_API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResResult {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResResult() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResTB_API.Resources.ResResult", typeof(ResResult).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after measure.
        /// </summary>
        public static string PR_afterActionString {
            get {
                return ResourceManager.GetString("PR_afterActionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Measure.
        /// </summary>
        public static string PR_BeforeAction {
            get {
                return ResourceManager.GetString("PR_BeforeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before measure.
        /// </summary>
        public static string PR_beforeActionString {
            get {
                return ResourceManager.GetString("PR_beforeActionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before vs. After Measure.
        /// </summary>
        public static string PR_BeforeVsAfter {
            get {
                return ResourceManager.GetString("PR_BeforeVsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure is cost-efficient.
        /// </summary>
        public static string PR_BenefitCostHigh {
            get {
                return ResourceManager.GetString("PR_BenefitCostHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-cost effective measure.
        /// </summary>
        public static string PR_BenefitCostLow {
            get {
                return ResourceManager.GetString("PR_BenefitCostLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realization to be discussed.
        /// </summary>
        public static string PR_BenefitCostMedium {
            get {
                return ResourceManager.GetString("PR_BenefitCostMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit / Cost - Ratio.
        /// </summary>
        public static string PR_BenefitCostRatio {
            get {
                return ResourceManager.GetString("PR_BenefitCostRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string PR_BenefitCostRatioString {
            get {
                return ResourceManager.GetString("PR_BenefitCostRatioString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit vs. Costs.
        /// </summary>
        public static string PR_BenefitVsCosts {
            get {
                return ResourceManager.GetString("PR_BenefitVsCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk - Indirect.
        /// </summary>
        public static string PR_CollectiveRiskIndirect {
            get {
                return ResourceManager.GetString("PR_CollectiveRiskIndirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk - Person.
        /// </summary>
        public static string PR_CollectiveRiskPerson {
            get {
                return ResourceManager.GetString("PR_CollectiveRiskPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk - Property.
        /// </summary>
        public static string PR_CollectiveRiskProperty {
            get {
                return ResourceManager.GetString("PR_CollectiveRiskProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk - Total.
        /// </summary>
        public static string PR_CollectiveRiskTotal {
            get {
                return ResourceManager.GetString("PR_CollectiveRiskTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Total - After Measure.
        /// </summary>
        public static string PR_CollectiveRiskTotalAfter {
            get {
                return ResourceManager.GetString("PR_CollectiveRiskTotalAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Total - Before Measure.
        /// </summary>
        public static string PR_CollectiveRiskTotalBefore {
            get {
                return ResourceManager.GetString("PR_CollectiveRiskTotalBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time of Project Result.
        /// </summary>
        public static string PR_CreationTime {
            get {
                return ResourceManager.GetString("PR_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Extent.
        /// </summary>
        public static string PR_DamageExtent {
            get {
                return ResourceManager.GetString("PR_DamageExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        public static string PR_DamageExtentDeaths {
            get {
                return ResourceManager.GetString("PR_DamageExtentDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Damage (with Resilience).
        /// </summary>
        public static string PR_DamageExtentIndirect {
            get {
                return ResourceManager.GetString("PR_DamageExtentIndirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Damage.
        /// </summary>
        public static string PR_DamageExtentPerson {
            get {
                return ResourceManager.GetString("PR_DamageExtentPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Damage.
        /// </summary>
        public static string PR_DamageExtentProperty {
            get {
                return ResourceManager.GetString("PR_DamageExtentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Damage.
        /// </summary>
        public static string PR_DamageExtentTotal {
            get {
                return ResourceManager.GetString("PR_DamageExtentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Risk.
        /// </summary>
        public static string PR_IndirectRisk {
            get {
                return ResourceManager.GetString("PR_IndirectRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Hazard.
        /// </summary>
        public static string PR_NatHazard {
            get {
                return ResourceManager.GetString("PR_NatHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Risk.
        /// </summary>
        public static string PR_PersonRisk {
            get {
                return ResourceManager.GetString("PR_PersonRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Risk.
        /// </summary>
        public static string PR_PropertyRisk {
            get {
                return ResourceManager.GetString("PR_PropertyRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Measure - Yearly Costs.
        /// </summary>
        public static string PR_ProtectionMeasureYearlyCosts {
            get {
                return ResourceManager.GetString("PR_ProtectionMeasureYearlyCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Periods.
        /// </summary>
        public static string PR_ReturnPeriods {
            get {
                return ResourceManager.GetString("PR_ReturnPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        public static string PR_Risk {
            get {
                return ResourceManager.GetString("PR_Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Total - Reduction.
        /// </summary>
        public static string PR_RiskReduction {
            get {
                return ResourceManager.GetString("PR_RiskReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Reduction.
        /// </summary>
        public static string PR_RiskReduktion2 {
            get {
                return ResourceManager.GetString("PR_RiskReduktion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly Costs.
        /// </summary>
        public static string PR_YearlyCosts {
            get {
                return ResourceManager.GetString("PR_YearlyCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Measure: LifeSpan can&apos;t be less than 1. Actual value: {0}.
        /// </summary>
        public static string PRJ_LifeSpanError {
            get {
                return ResourceManager.GetString("PRJ_LifeSpanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No damage extent for project. Consider rerunning the computation..
        /// </summary>
        public static string PRJ_NoDamageExtent {
            get {
                return ResourceManager.GetString("PRJ_NoDamageExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no project.
        /// </summary>
        public static string PRJ_NoProject {
            get {
                return ResourceManager.GetString("PRJ_NoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID {0} not found..
        /// </summary>
        public static string PRJ_ProjectNotFound {
            get {
                return ResourceManager.GetString("PRJ_ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect Damage (with Resilience).
        /// </summary>
        public static string SR_DamageExtentIndirectResilient {
            get {
                return ResourceManager.GetString("SR_DamageExtentIndirectResilient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Period.
        /// </summary>
        public static string SR_ReturnPeriod {
            get {
                return ResourceManager.GetString("SR_ReturnPeriod", resourceCulture);
            }
        }
    }
}
