//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResTB_API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResSummary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResSummary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResTB_API.Resources.ResSummary", typeof(ResSummary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after measure.
        /// </summary>
        public static string TXT_afterMeasure {
            get {
                return ResourceManager.GetString("TXT_afterMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before measure.
        /// </summary>
        public static string TXT_beforeMeasure {
            get {
                return ResourceManager.GetString("TXT_beforeMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit / Cost Ratio.
        /// </summary>
        public static string TXT_BenefitCostRatio {
            get {
                return ResourceManager.GetString("TXT_BenefitCostRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        public static string TXT_CollectiveRisk {
            get {
                return ResourceManager.GetString("TXT_CollectiveRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Extent.
        /// </summary>
        public static string TXT_DamageExtent {
            get {
                return ResourceManager.GetString("TXT_DamageExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string TXT_ErrorsWarning {
            get {
                return ResourceManager.GetString("TXT_ErrorsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Word.
        /// </summary>
        public static string TXT_ExportWord {
            get {
                return ResourceManager.GetString("TXT_ExportWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect.
        /// </summary>
        public static string TXT_Indirect {
            get {
                return ResourceManager.GetString("TXT_Indirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string TXT_Log {
            get {
                return ResourceManager.GetString("TXT_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string TXT_Message {
            get {
                return ResourceManager.GetString("TXT_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TXT_Name {
            get {
                return ResourceManager.GetString("TXT_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard.
        /// </summary>
        public static string TXT_NatHazard {
            get {
                return ResourceManager.GetString("TXT_NatHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string TXT_Number {
            get {
                return ResourceManager.GetString("TXT_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of.
        /// </summary>
        public static string TXT_NumberOf {
            get {
                return ResourceManager.GetString("TXT_NumberOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string TXT_Person {
            get {
                return ResourceManager.GetString("TXT_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string TXT_Print {
            get {
                return ResourceManager.GetString("TXT_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Details.
        /// </summary>
        public static string TXT_PrintDetail {
            get {
                return ResourceManager.GetString("TXT_PrintDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string TXT_Process {
            get {
                return ResourceManager.GetString("TXT_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string TXT_Processes {
            get {
                return ResourceManager.GetString("TXT_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes in Detail.
        /// </summary>
        public static string TXT_ProcessesDetail {
            get {
                return ResourceManager.GetString("TXT_ProcessesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string TXT_Project {
            get {
                return ResourceManager.GetString("TXT_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Summary.
        /// </summary>
        public static string TXT_ProjectSummary {
            get {
                return ResourceManager.GetString("TXT_ProjectSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string TXT_Property {
            get {
                return ResourceManager.GetString("TXT_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Measure.
        /// </summary>
        public static string TXT_ProtectionMeasure {
            get {
                return ResourceManager.GetString("TXT_ProtectionMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report template.
        /// </summary>
        public static string TXT_ReportTemplate {
            get {
                return ResourceManager.GetString("TXT_ReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk by process type.
        /// </summary>
        public static string TXT_RiskPerProcess {
            get {
                return ResourceManager.GetString("TXT_RiskPerProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string TXT_Scenario {
            get {
                return ResourceManager.GetString("TXT_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string TXT_Scenarios {
            get {
                return ResourceManager.GetString("TXT_Scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show warnings on map.
        /// </summary>
        public static string TXT_ShowWarningsOnMap {
            get {
                return ResourceManager.GetString("TXT_ShowWarningsOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string TXT_Summary {
            get {
                return ResourceManager.GetString("TXT_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TXT_Total {
            get {
                return ResourceManager.GetString("TXT_Total", resourceCulture);
            }
        }
    }
}
