//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResTB.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResTB.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiResiliencia Honduras Desktop.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage potential.
        /// </summary>
        public static string DamagePotential {
            get {
                return ResourceManager.GetString("DamagePotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string GUI_Help {
            get {
                return ResourceManager.GetString("GUI_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard map.
        /// </summary>
        public static string Hazard_Map {
            get {
                return ResourceManager.GetString("Hazard_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard maps (after measure).
        /// </summary>
        public static string Hazard_Maps_after_Measure {
            get {
                return ResourceManager.GetString("Hazard_Maps_after_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard maps (before measure).
        /// </summary>
        public static string Hazard_Maps_before_Measure {
            get {
                return ResourceManager.GetString("Hazard_Maps_before_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to minimize.
        /// </summary>
        public static string Info_DoubleClick_Minimize {
            get {
                return ResourceManager.GetString("Info_DoubleClick_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End editing.
        /// </summary>
        public static string Info_Edit_End {
            get {
                return ResourceManager.GetString("Info_Edit_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to exit, ESC key to delete faulty polygons.
        /// </summary>
        public static string Info_Edit_Polygone {
            get {
                return ResourceManager.GetString("Info_Edit_Polygone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit layer to view.
        /// </summary>
        public static string Layer_Fit {
            get {
                return ResourceManager.GetString("Layer_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide layer.
        /// </summary>
        public static string Layer_Hide {
            get {
                return ResourceManager.GetString("Layer_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move layer to the bottom.
        /// </summary>
        public static string Layer_Move_Bottom {
            get {
                return ResourceManager.GetString("Layer_Move_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move layer down.
        /// </summary>
        public static string Layer_Move_Down {
            get {
                return ResourceManager.GetString("Layer_Move_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move layer to the top.
        /// </summary>
        public static string Layer_Move_Top {
            get {
                return ResourceManager.GetString("Layer_Move_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move layer up.
        /// </summary>
        public static string Layer_Move_Up {
            get {
                return ResourceManager.GetString("Layer_Move_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove layer.
        /// </summary>
        public static string Layer_Remove {
            get {
                return ResourceManager.GetString("Layer_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show layer.
        /// </summary>
        public static string Layer_Show {
            get {
                return ResourceManager.GetString("Layer_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map control.
        /// </summary>
        public static string Map_Control {
            get {
                return ResourceManager.GetString("Map_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor mode.
        /// </summary>
        public static string Map_Cursor_Mode {
            get {
                return ResourceManager.GetString("Map_Cursor_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping.
        /// </summary>
        public static string Map_Mapping {
            get {
                return ResourceManager.GetString("Map_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        public static string Map_Pan {
            get {
                return ResourceManager.GetString("Map_Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string Map_Zoom_In {
            get {
                return ResourceManager.GetString("Map_Zoom_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string Map_Zoom_Out {
            get {
                return ResourceManager.GetString("Map_Zoom_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation Measure.
        /// </summary>
        public static string MitigationMeasure {
            get {
                return ResourceManager.GetString("MitigationMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database OK.
        /// </summary>
        public static string Msg_Db_Connected {
            get {
                return ResourceManager.GetString("Msg_Db_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Database .
        /// </summary>
        public static string Msg_Db_Disconnected {
            get {
                return ResourceManager.GetString("Msg_Db_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet.
        /// </summary>
        public static string Msg_Internet_No {
            get {
                return ResourceManager.GetString("Msg_Internet_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet OK.
        /// </summary>
        public static string Msg_Internet_Ok {
            get {
                return ResourceManager.GetString("Msg_Internet_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string Project_Create {
            get {
                return ResourceManager.GetString("Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Project.
        /// </summary>
        public static string Project_Export {
            get {
                return ResourceManager.GetString("Project_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project list.
        /// </summary>
        public static string Project_List {
            get {
                return ResourceManager.GetString("Project_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project management.
        /// </summary>
        public static string Project_Management {
            get {
                return ResourceManager.GetString("Project_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string Project_Name {
            get {
                return ResourceManager.GetString("Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string Project_New {
            get {
                return ResourceManager.GetString("Project_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project number.
        /// </summary>
        public static string Project_Number {
            get {
                return ResourceManager.GetString("Project_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string Project_Open {
            get {
                return ResourceManager.GetString("Project_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project perimeter.
        /// </summary>
        public static string Project_Perimeter {
            get {
                return ResourceManager.GetString("Project_Perimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        public static string Project_Save {
            get {
                return ResourceManager.GetString("Project_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add raster file.
        /// </summary>
        public static string Raster_Add {
            get {
                return ResourceManager.GetString("Raster_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience.
        /// </summary>
        public static string Resilience {
            get {
                return ResourceManager.GetString("Resilience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience (after measure).
        /// </summary>
        public static string Resilience_after_Measure {
            get {
                return ResourceManager.GetString("Resilience_after_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience (before measure).
        /// </summary>
        public static string Resilience_before_Measure {
            get {
                return ResourceManager.GetString("Resilience_before_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Tab_Map {
            get {
                return ResourceManager.GetString("Tab_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
